### ISSUE TITLE
make.sh

### ISSUE THREAD

**Issue by lhlm1994** [fundamentalvision/Deformable-DETR#10] opened 2020-12-10 10:03 UTC
when I run sh ./make.sh, I got this message:

Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] :/home1/hli/cuda10.2/bin/nvcc -DWITH_CUDA -I/home1/hli/Deformable-DETR/models/ops/src -I/home1/hli/anaconda3/envs/detr/lib/python3.7/site-packages/torch/include -I/home1/hli/anaconda3/envs/detr/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home1/hli/anaconda3/envs/detr/lib/python3.7/site-packages/torch/include/TH -I/home1/hli/anaconda3/envs/detr/lib/python3.7/site-packages/torch/include/THC -I:/home1/hli/cuda10.2/include -I/home1/hli/anaconda3/envs/detr/include/python3.7m -c -c /home1/hli/Deformable-DETR/models/ops/src/cuda/ms_deform_attn_cuda.cu -o /home1/hli/Deformable-DETR/models/ops/build/temp.linux-x86_64-3.7/home1/hli/Deformable-DETR/models/ops/src/cuda/ms_deform_attn_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=MultiScaleDeformableAttention -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
FAILED: /home1/hli/Deformable-DETR/models/ops/build/temp.linux-x86_64-3.7/home1/hli/Deformable-DETR/models/ops/src/cuda/ms_deform_attn_cuda.o
:/home1/hli/cuda10.2/bin/nvcc -DWITH_CUDA -I/home1/hli/Deformable-DETR/models/ops/src -I/home1/hli/anaconda3/envs/detr/lib/python3.7/site-packages/torch/include -I/home1/hli/anaconda3/envs/detr/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home1/hli/anaconda3/envs/detr/lib/python3.7/site-packages/torch/include/TH -I/home1/hli/anaconda3/envs/detr/lib/python3.7/site-packages/torch/include/THC -I:/home1/hli/cuda10.2/include -I/home1/hli/anaconda3/envs/detr/include/python3.7m -c -c /home1/hli/Deformable-DETR/models/ops/src/cuda/ms_deform_attn_cuda.cu -o /home1/hli/Deformable-DETR/models/ops/build/temp.linux-x86_64-3.7/home1/hli/Deformable-DETR/models/ops/src/cuda/ms_deform_attn_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=MultiScaleDeformableAttention -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
/bin/sh: 1: :/home1/hli/cuda10.2/bin/nvcc: not found
[2/3] c++ -MMD -MF /home1/hli/Deformable-DETR/models/ops/build/temp.linux-x86_64-3.7/home1/hli/Deformable-DETR/models/ops/src/cpu/ms_deform_attn_cpu.o.d -pthread -B /home1/hli/anaconda3/envs/detr/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home1/hli/Deformable-DETR/models/ops/src -I/home1/hli/anaconda3/envs/detr/lib/python3.7/site-packages/torch/include -I/home1/hli/anaconda3/envs/detr/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home1/hli/anaconda3/envs/detr/lib/python3.7/site-packages/torch/include/TH -I/home1/hli/anaconda3/envs/detr/lib/python3.7/site-packages/torch/include/THC -I:/home1/hli/cuda10.2/include -I/home1/hli/anaconda3/envs/detr/include/python3.7m -c -c /home1/hli/Deformable-DETR/models/ops/src/cpu/ms_deform_attn_cpu.cpp -o /home1/hli/Deformable-DETR/models/ops/build/temp.linux-x86_64-3.7/home1/hli/Deformable-DETR/models/ops/src/cpu/ms_deform_attn_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=MultiScaleDeformableAttention -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home1/hli/Deformable-DETR/models/ops/build/temp.linux-x86_64-3.7/home1/hli/Deformable-DETR/models/ops/src/cpu/ms_deform_attn_cpu.o
c++ -MMD -MF /home1/hli/Deformable-DETR/models/ops/build/temp.linux-x86_64-3.7/home1/hli/Deformable-DETR/models/ops/src/cpu/ms_deform_attn_cpu.o.d -pthread -B /home1/hli/anaconda3/envs/detr/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home1/hli/Deformable-DETR/models/ops/src -I/home1/hli/anaconda3/envs/detr/lib/python3.7/site-packages/torch/include -I/home1/hli/anaconda3/envs/detr/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home1/hli/anaconda3/envs/detr/lib/python3.7/site-packages/torch/include/TH -I/home1/hli/anaconda3/envs/detr/lib/python3.7/site-packages/torch/include/THC -I:/home1/hli/cuda10.2/include -I/home1/hli/anaconda3/envs/detr/include/python3.7m -c -c /home1/hli/Deformable-DETR/models/ops/src/cpu/ms_deform_attn_cpu.cpp -o /home1/hli/Deformable-DETR/models/ops/build/temp.linux-x86_64-3.7/home1/hli/Deformable-DETR/models/ops/src/cpu/ms_deform_attn_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=MultiScaleDeformableAttention -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home1/hli/Deformable-DETR/models/ops/src/cpu/ms_deform_attn_cpu.cpp:14:0:
/home1/hli/anaconda3/envs/detr/lib/python3.7/site-packages/torch/include/ATen/cuda/CUDAContext.h:5:30: fatal error: cuda_runtime_api.h: No such file or directory
compilation terminated.

my Cuda version is 10.2.89, the other settings are the same as yours, torch 1.5.1 python3.7. Can you help me? thanks

**Comment by jackroos** [comment] 2020-12-10 10:59
Hi @lhlm1994

Could you check whether your PyTorch is successfully installed with CUDA support by running the following scripts in python:
```python
import torch
print(torch.cuda.is_available())
```

**Comment by lhlm1994** [comment] 2020-12-10 12:24
> Hi @lhlm1994
> 
> Could you check whether your PyTorch is successfully installed with CUDA support by running the following scripts in python:
> 
> ```python
> import torch
> print(torch.cuda.is_available())
> ```

yes, it is available,  maybe only cuda9.2 works?

**Comment by jackroos** [comment] 2020-12-10 12:40
Do you add CUDA 'lib64' path to $LD_LIBRARY_PATH? And do you add CUDA 'bin' path to $PATH? 
You can check by:
```bash
echo $PATH
echo $LD_LIBRARY_PATH
```

**Comment by lhlm1994** [comment] 2020-12-10 12:55
> ```shell
> ```shell
> echo $LD_LIBRARY_PATH
> ```
> 
> 
>       
> ```

echo $LD_LIBRARY_PATH
/home1/hli/cuda10.2/lib64:/usr/local/cuda-10.0/lib64:/home1/hli/cuda10.2/lib64

(detr) hli@miracle:~/Deformable-DETR/models/ops$ echo $PATH
/home1/hli/cuda10.2/bin:/home1/hli/bin:/home1/hli/.local/bin:/home1/hli/cuda10.2/bin:/home1/hli/anaconda3/envs/detr/bin:/home1/hli/anaconda3/condabin:/usr/local/cuda-10.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

yes, I added. >_<!

**Comment by lhlm1994** [comment] 2020-12-10 14:53
icant find these files :/cpu/ms_deform_attn_cpu.o  and /ops/src/cuda/ms_deform_attn_cuda.o:  can you add them?

**Comment by jackroos** [comment] 2020-12-11 03:04
The .o file is generated in the compiling stage.

**Comment by yunren** [comment] 2020-12-15 12:12
Do you solve it? How? I met same problem too

**Comment by JarintotionDin** [comment] 2020-12-22 10:38
I met this problem too, and I solved it by  changing 'CUDA_HOME=CUDA_HOME:/usr/local/cuda-11.0' to 'export CUDA_HOME=/usr/local/cuda-11.0'. 
  if torch.cuda.is_available() and CUDA_HOME is not None:
      extension = CUDAExtension
      sources += source_cuda
      define_macros += [("WITH_CUDA", None)]
      extra_compile_args["nvcc"] = [
          "-DCUDA_HAS_FP16=1",
          "-D__CUDA_NO_HALF_OPERATORS__",
          "-D__CUDA_NO_HALF_CONVERSIONS__",
          "-D__CUDA_NO_HALF2_OPERATORS__",
      ]
  else:
      raise NotImplementedError('Cuda is not availabel')

When I use  'CUDA_HOME=CUDA_HOME:/usr/local/cuda-11.0' , the CUDA_HOME is None!

**Comment by yunren** [comment] 2020-12-23 01:38
> I met this problem too, and I solved it by changing 'CUDA_HOME=CUDA_HOME:/usr/local/cuda-11.0' to 'export CUDA_HOME=/usr/local/cuda-11.0'.
> if torch.cuda.is_available() and CUDA_HOME is not None:
> extension = CUDAExtension
> sources += source_cuda
> define_macros += [("WITH_CUDA", None)]
> extra_compile_args["nvcc"] = [
> "-DCUDA_HAS_FP16=1",
> "-D__CUDA_NO_HALF_OPERATORS__",
> "-D__CUDA_NO_HALF_CONVERSIONS__",
> "-D__CUDA_NO_HALF2_OPERATORS__",
> ]
> else:
> raise NotImplementedError('Cuda is not availabel')
> 
> When I use 'CUDA_HOME=CUDA_HOME:/usr/local/cuda-11.0' , the CUDA_HOME is None!

So nice！
my problem is also solved just as you do.

**Comment by jackroos** [comment] 2020-12-30 02:37
@JarintotionDin Thank you for sharing the solution. Since the problem is solved, I will close this issue.

**Closed as completed by jackroos** 2020-12-30 02:37 UTC

**Comment by kuiran** [comment] 2021-03-06 11:51
Great! It works.

**Comment by wsz912** [comment] 2021-04-26 15:22
It works.

**Comment by ts-kim** [comment] 2021-05-22 07:09
export CUDA_HOME=/usr/local/cuda-11.0 
sh make.sh

It works! Thank you for nice solution.

**Comment by makabakasu** [comment] 2021-06-02 05:15
export CUDA_HOME=/usr/local/cuda-11.0
sh make.sh
it works~ Thanks!

**Comment by everRoc** [comment] 2021-08-31 09:56
thank you so much!

**Comment by XDhughie** [comment] 2022-06-09 07:00
g++: error: /home/lh/trackformer-main/src/trackformer/models/ops/build/temp.linux-x86_64-3.7/home/lh/trackformer-main/src/trackformer/models/ops/src/cpu/ms_deform_attn_cpu.o: No such file or directory
g++: error: /home/lh/trackformer-main/src/trackformer/models/ops/build/temp.linux-x86_64-3.7/home/lh/trackformer-main/src/trackformer/models/ops/src/vision.o: No such file or directory

still error，how to do with that？

**Comment by wangjiacong1996** [comment] 2023-04-05 13:49
it works！thank you~

**Comment by FocusGZL** [comment] 2024-09-27 07:13
> g++: error: /home/lh/trackformer-main/src/trackformer/models/ops/build/temp.linux-x86_64-3.7/home/lh/trackformer-main/src/trackformer/models/ops/src/cpu/ms_deform_attn_cpu.o: No such file or directory g++: error: /home/lh/trackformer-main/src/trackformer/models/ops/build/temp.linux-x86_64-3.7/home/lh/trackformer-main/src/trackformer/models/ops/src/vision.o: No such file or directory
> 
> still error，how to do with that？

have you resolved the problem?
